# Version of docker compose. See https://docs.docker.com/compose/compose-file/compose-versioning/#versioning
version: "3"

# Containers
services:

  mongodb:
    image: mongo # name of image in docker hub
    container_name: mongo-docker
    ports:
      - "27017:27017" # map listen port of container with port of running computer
    environment:
      - MONGO_INITDB_ROOT_USERNAME=halab
      - MONGO_INITDB_ROOT_PASSWORD=superman
    volumes:
      - "/opt/docker/mongo:/data/db" # map folder /data/db in container with folder /opt/docker/mongo in running computer
    networks:
      - docker-example

  application:
    image: openjdk:8
    container_name: application-docker
    depends_on:
      - mongodb
    volumes:
      - /opt/docker/application:/opt/application
    command: java -jar /opt/application/docker-example-1.0-SNAPSHOT.jar
    networks:
      - docker-example

networks: 
  docker-example:
